### PR TITLE
Update StandardPaths.podspec.json

### PR DESCRIPTION
**Pull request by Ashton-W**
enabled ARC in podspec

Merge if #7 is confirmed :+1:

### CODE REVIEW

**Comment by Ashton-W** [comment]
Should we return to a ruby podspec over json? CocoaPods trunk will convert it.

**Comment by nicklockwood** [comment]
Hmm. There shouldn't be. The only [[alloc] init]'s that I can see are inside dispatch_once clauses. I'll take a look.

**Comment by nicklockwood** [comment]
Ah OK, was it just in the heightSuffix method that you were seeing it?

**Comment by Ashton-W** [comment]
Do you mean to merge this @nicklockwood?
Yes thats the spot. In #7 I mention that the test project is building with ARC. Are you saying that it supports being built as ARC and non-ARC?

**Pull request merged**
